# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Data Analysis',  url: 'data-analysis'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}
- {name: 'Privacy Policy',            url: 'privacy'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link:   'mailto:sylvumeris.lab@gmail.com'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/company/111355042/admin/dashboard/'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
# pagination:
#   next_page: 'Newer'
#   previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

